{% set name = "sarge" %}
{% set version = "0.1.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sarge-{{ version }}.tar.gz
  sha256: f48fb904e64f10ad6bef62422eaf4736acfd9b13ab64ba44822637a9dbb53265

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - sarge

about:
  home: http://sarge.readthedocs.io/en/latest/
  license: BSD 3-clause
  license_family: BSD
  summary: a wrapper for subprocess for interaction with external applications
  license_file: LICENSE
  doc_url: http://sarge.readthedocs.io/en/latest/
  dev_url: https://bitbucket.org/vinay.sajip/sarge

extra:
  recipe-maintainers:
    - takluyver
    - fangohr
    - marijanbeg
    - davidcortesortuno
    - igortg
