{% set name = "sarge" %}
{% set version = "0.1.5" %}
{% set sha256 = "8e61e12d1024b2b363746322a36f0c31ec998ff2b069f42c8c0ed286747dd0ee" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - sarge

about:
  home: http://sarge.readthedocs.io/en/latest/
  license: BSD 3-clause
  license_family: BSD
  summary: a wrapper for subprocess for interaction with external applications
  license_file: LICENSE
  doc_url: http://sarge.readthedocs.io/en/latest/
  dev_url: https://bitbucket.org/vinay.sajip/sarge

extra:
  recipe-maintainers:
    - takluyver
    - fangohr
    - mb1a15
    - davidcortesortuno
