{% set name = "sarge" %}
{% set version = "0.1.5" %}
{% set sha256 = "da8cc90883f8e5ab4af0d746438f608662f5f2a35da2e858517927edefa134b0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.post0.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - sarge

about:
  home: http://sarge.readthedocs.io/en/latest/
  license: BSD 3-clause
  license_family: BSD
  summary: a wrapper for subprocess for interaction with external applications
  license_file: LICENSE
  doc_url: http://sarge.readthedocs.io/en/latest/
  dev_url: https://bitbucket.org/vinay.sajip/sarge

extra:
  recipe-maintainers:
    - takluyver
    - fangohr
    - marijanbeg
    - davidcortesortuno
