travis:
  secure:
    BINSTAR_TOKEN: MR+afWItqL9THxklFV4V5YUIh/1PrAUUv802qEb/WvU3LcpkVp/63AWuGjddSWFm53CQBh1NhqAVPHW/GDgD85KWUwI6fnVWKsjcL3tEIPZ21/3NV7nY0o7w0OaUCD9TTWrHBoSEJqG7kf1cm6QcX1+cA98+NTPyPEE0/PLCDhat/rsiV2MowY5sATTkYpmnJMneIfgWkU4d6Bals2JTn6EoIeDf4a0BqujIlY2PEVa+jeflWfeOwJgdkqDrxiaerZCKZY4v/ajZA6xiGsctlhJYc35OYss2Akl/TfGKvzZFaxEbdDB6WI+9qHhk8avxoW8XK1jTAaIxtXquG29qIFfZXsam6t2445f8nsG8q2S234HJyzyjOruZNmNlCEg+2TYavC1A7r3Ovms4tovMi68geA0h9BMC2sF9WrbaGIpPEfziKtNFTDRyDf4PSFNkKq5rZ2Q3GqfYZDMbEyCACTgA8MPHdY4+0mL4VU3IdB6X7ECsXzUC0Vo/4sL4vn7IoqT8XYCR9Kht75yBy95W385INTFZ+ksIi+GqIDJu4oekzmG5Q77c5mjockBnqFOKwcr675l2zfXbJwTEV2wwZl1Z9a4VFRSXf9cV1U1XRkqcozvdJIjQsYkkyhBj8fqpSf5lq+VBb6xwxXfOh8YuanNdEqtq/XJnNDVsCGvsPLk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
