travis:
  secure:
    BINSTAR_TOKEN: KqY0dkwXopCoW4PEugYzwte6Clh3KYti41vigqDQrEWm7yT2En21PaQxY31SYgvW414+0QRIxIdMkeuAQq/M2ik34gCwk4lHjntdWvcVef5Uruiy92xVX8XOLK1SRMbDW4IYwZ4d9OztkOYP8wJG6FWvTuB56vmEdGFE4VhzFneEnTaiWG8buvPWWLlswXiwPhphsSaExsErAS/lfxvITnm2bUTFUuaG/9+Ok9+H2+u+dWkos8X8AjDpczjX9JQje8moEI0hArW3txhPH3lM5grZWMZUsB6UzIq5/F/fQe5/hd264h530rqjhbtkpYIQUAgrL7i8uPE5YRqvt/M0ToLkfzfSVL59X+yxGNmbLZLxEAoiKdFb4tjUlANbrCZOnbPQ7UB3OdKsIh7UPM9PR5ZBBPlXIAKuV261Qeqpjri6CWbxE3gdU/5boS8QHQO84brZ8b76alZBwEjm/55Z/P/DVC7WTQlU9C8G0FcaKHpgFtm+yxGtgML70KmkCEfmUujIJUyKSWrhbHVBebouci1L9ib2rXiiqGx9z06+42OK9VRrUthdzsy4iQ1qv7wub8Eryulb0CSDzzupxof23NEwtwxBLh6i9u+l/BbGQNScVeGEgJZ3G3F/0kByxeKDJuNC6TG65FAm/d8KTKm9mO0R21v/HulKgAifIk/O3V8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
